# Generated by Django 2.1.3 on 2018-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearchCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='caTag',
        ),
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='catagory',
            field=models.CharField(default='DefaultCatagory', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='htmlPage',
            field=models.CharField(default='DefaultHtml', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='sourceLink',
            field=models.URLField(default='DefaultSource', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='tag',
            field=models.CharField(default='DefaultTag', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.TextField(default='DefaultText'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CaTag',
        ),
    ]
