# Generated by Django 2.1.3 on 2018-12-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlSearchCenter', '0002_auto_20181113_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
